baseurl: /lovelace
title: THEORETICAL MODELING
author: Mark Blokpoel and Iris van Rooij
simple_search: http://google.com/search
description: for cognitive science and psychology
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:collection/:name
timezone: Europe/Amsterdam
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Rakefile'
  - 'UploadToGithub.Rakefile'
  - 'README.md'
  - '*.sh'
  - 'content/_part_iv'
  - 'content/part4.md'

plugins:
  - jekyll/scholar
  - jekyll-youtube

scholar:
  style: apa
  sort_by: author

scalafiddle:
  theme: light

collections_dir: content

collections:
  part_i:
    sort_by: chapter
    output: true
  part_ii:
    sort_by: chapter
    output: true
  part_iii:
    sort_by: chapter
    output: true
  part_iv:
    sort_by: chapter
    output: true

git:
  branch: master
